CREATE OR REPLACE PROCEDURE COMPARE_SCHEMAS (
    DEV_SCHEMA_NAME IN VARCHAR2,
    PROD_SCHEMA_NAME IN VARCHAR2
) AS
    TYPE STR_LIST IS TABLE OF VARCHAR(100);
    
    DEV_TABLES STR_LIST := STR_LIST();
    PROD_TABLES STR_LIST := STR_LIST();
    
BEGIN 
    SELECT TABLE_NAME BULK COLLECT INTO DEV_TABLES
    FROM ALL_TABLES
    WHERE OWNER = DEV_SCHEMA_NAME;
    
    SELECT TABLE_NAME BULK COLLECT INTO PROD_TABLES
    FROM ALL_TABLES
    WHERE OWNER = PROD_SCHEMA_NAME;
END COMPARE_SCHEMAS;

CALL compare_schemas('C##DEV', 'C##PROD');

