drop table c##dev.products;
drop table c##prod.products;

-- DEV --

CREATE TABLE C##DEV.CATEGORY (
    ID NUMBER NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    CONSTRAINT PK_ID_CT PRIMARY KEY (ID)
);

CREATE TABLE C##DEV.PRODUCT (
    ID NUMBER NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    CATEGORY_ID NUMBER NOT NULL,
    CONSTRAINT PK_ID_PR PRIMARY KEY (ID),
    CONSTRAINT FK_CR FOREIGN KEY (CATEGORY_ID) REFERENCES C##DEV.CATEGORY (ID)
);

-- PROD --

CREATE TABLE C##PROD.CATEGORY (
    ID NUMBER NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    CONSTRAINT PK_ID_CT PRIMARY KEY (ID)
);

CREATE TABLE C##PROD.PRODUCT (
    ID NUMBER NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    CATEGORY_ID NUMBER NOT NULL,
    CONSTRAINT PK_ID_PR PRIMARY KEY (ID),
    CONSTRAINT FK_CR FOREIGN KEY (CATEGORY_ID) REFERENCES C##PROD.CATEGORY (ID)
);